// <auto-generated />
using GameNetManager.Server.Data;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace GameNetManager.Server.Data.Migrations;

/// <summary>
/// Restores EF Core migration metadata for migrations that were checked in
/// without their generated Designer files. The migration Up/Down implementations
/// remain in their original files and are not changed here.
/// </summary>

[DbContext(typeof(GameNetDbContext))]
[Migration("20261002080000_InvoicePayments")]
partial class InvoicePayments
{
}

[DbContext(typeof(GameNetDbContext))]
[Migration("20261002081500_SessionDetails")]
partial class SessionDetails
{
}

[DbContext(typeof(GameNetDbContext))]
[Migration("20261002083000_CustomerFreeBenefits")]
partial class CustomerFreeBenefits
{
}

[DbContext(typeof(GameNetDbContext))]
[Migration("20261002084000_CustomerConcurrentLogin")]
partial class CustomerConcurrentLogin
{
}

[DbContext(typeof(GameNetDbContext))]
[Migration("20261002090000_WalletRefundReference")]
partial class WalletRefundReference
{
}

[DbContext(typeof(GameNetDbContext))]
[Migration("20261002110000_CustomerFinanceIdentity")]
partial class CustomerFinanceIdentity
{
}

[DbContext(typeof(GameNetDbContext))]
[Migration("20261002113000_InvoiceReverseCore")]
partial class InvoiceReverseCore
{
}

[DbContext(typeof(GameNetDbContext))]
[Migration("20261002130000_CustomerIdentityVipTier")]
partial class CustomerIdentityVipTier
{
}

[DbContext(typeof(GameNetDbContext))]
[Migration("20261002133000_VipPackageDomain")]
partial class VipPackageDomain
{
}


[DbContext(typeof(GameNetDbContext))]
[Migration("20261002135000_CustomerCredentials")]
partial class CustomerCredentials
{
}


[DbContext(typeof(GameNetDbContext))]
[Migration("20261002150000_BuffetInventorySettings")]
partial class BuffetInventorySettings
{
}

[DbContext(typeof(GameNetDbContext))]
[Migration("20261002170000_BuffetTransactionPricing")]
partial class BuffetTransactionPricing
{
}

[DbContext(typeof(GameNetDbContext))]
[Migration("20261002183000_InventoryTransactionInvoiceReference")]
partial class InventoryTransactionInvoiceReference
{
}

[DbContext(typeof(GameNetDbContext))]
[Migration("20261002190000_UserAuthorizationAndApprovals")]
partial class UserAuthorizationAndApprovals
{
}


[DbContext(typeof(GameNetDbContext))]
[Migration("20261002193000_EmployeePayroll")]
partial class EmployeePayroll
{
}

[DbContext(typeof(GameNetDbContext))]
[Migration("20261002194500_AgentDeviceFoundation")]
partial class AgentDeviceFoundation
{
}
